# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

# Install build dependencies needed for building Python packages
RUN apt-get update && apt-get install -y gcc build-essential && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip
RUN pip install --upgrade pip

# Install the package and its dependencies
RUN pip install .

# Set the entrypoint to the MCP server command
CMD ["adb-mysql-mcp-server"]
